### ISSUE TITLE
btrfs_map_physical.c does not give the correct physical offset

### ISSUE THREAD

**Issue by sreyan32** [osandov/osandov-linux#2]
I have a swap file on a sub volume which is separate from my root sub volume.

I tried calculating the Physical Offset for it using btrfs_map_physical.c but it turns out to be incorrect.

**Comment by crabdancing** [comment]
Did you divide by page size? This worked fine for me.

**Comment by sreyan32** [comment]
Yes it worked for me.

**Comment by crabdancing** [comment]
Cool :) I recommend closing this issue if problem is solved! ^_^
