### ISSUE TITLE
License or permission to distribute

### ISSUE THREAD

**Issue by aeryxium** [osandov/osandov-linux#3]
Hello,

I noticed that no license is specified for this repo or in the individual source. I was hoping to include a compiled version of btrfs_map_physical.c in a repo of mine, but without a license specified I'm unable to do so without permission. Can you confirm what license pertains to this repo, or barring that are you willing to explicitly give permission to distribute?

Thanks

**Comment by osandov** [comment]
Hi, I just licensed it under the MIT license. I hope that works for you. Thanks for reaching out!

**Comment by aeryxium** [comment]
Works perfectly, thanks!
